# Generated by Django 4.2.7 on 2025-07-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_internshipapplication_area_of_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('checkin_time', models.TimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='internship.internshipapplication')),
            ],
            options={
                'ordering': ['-date', '-checkin_time'],
                'unique_together': {('intern', 'date')},
            },
        ),
    ]
