# Generated by Django 4.2.7 on 2025-07-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_internshipapplication_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('period', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Software', 'Software'), ('Admin/HR', 'Admin/HR')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internship.internshippackage'),
        ),
    ]
