# Generated by Django 4.2.7 on 2025-07-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_profile_profile_photo'),
    ]

    operations = [
    ]
